### ISSUE TITLE
Schreibfehler in der Übersichtsgrafik

### ISSUE THREAD

**Issue by dominiczedler** [LuisMossburger/Digitale_Safari#1]
Hi, kurz mal bei dir reingeschaut - ich habe einen kleinen Schreibfehler in der [Übersichtsgrafik](https://raw.githubusercontent.com/LuisMossburger/Digitale_Safari/master/DigitaleSafari.jpg) gefunden: Links oben in der Ecke steht nicht Bibliothek, sondern Bibliothe_**i**_k.

Das Projekt sieht sehr toll aus, gute Arbeit :)

**Comment by LuisMossburger** [comment]
Tut mir Leid, dein issue wurde mir irgendwie nicht angezeigt.
Jetzt jedenfalls gefixed und danke für den Hinweis und das Kompliment! :)
